### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by matteo-rigon** [nlemoine/wp-cli-fixtures#1]
Hi, first of all thank you for this awesome package.
My company is considering to adopt it for our local WP development and we'd like to have these features discussed:

- a new Option entity. We heavily rely on the Advanced Custom Field plugin and while we can already easily set meta data for posts, users, and terms we would like to have the possibility to feed the wp_options table as well
- the ability to keep pages when deleting posts. Usually when developing sites we always have a predetermined set of pages that should always exist. We would like to have a way to keep pages when deleting fake data and instead just delete their meta data and post_content

**Comment by nlemoine** [comment]
Hi @reegodev, 

### Option entity

I already thought about adding options but they can't really be considered as an entity. There's no "model", no metadata table. It makes then harder to handle them in a package like this. You can't flag them as "fake". `add_option`/`update_option` doesn't return even the option ID as it's a key/value model.

However, most of your content is supposed to be stored out of the options table. Any reason/use case why you would need to generate fake data in the options table? This package isn't intended to set options, It's focused on content. Maybe [Dictator](https://github.com/danielbachhuber/dictator) is what you're looking for?

### Ability to keep pages when deleting posts

IMHO, this is a very specific feature request of your specific workflow. Someone could ask to keep some specific post type, some specific terms from a custom taxonomy, etc.

You can easily delete the `_fake` meta of pages by running this query:
```bash
wp db query "DELETE wp_postmeta FROM wp_postmeta INNER JOIN wp_posts ON wp_posts.ID = wp_postmeta.post_id WHERE wp_postmeta.meta_key = '_fake' AND wp_posts.post_type = 'page'"
```
Pages won't then deleted when running `wp fixtures delete`.

This package is about generating fake content, I'd like to keep it that way for now. I may reconsider this if others users ask for it.
