### ISSUE TITLE
Publish a new release?

### ISSUE THREAD

**Issue by jenkoian** [nlemoine/wp-cli-fixtures#12]
It's been quite a while since you've published a new release (https://github.com/nlemoine/wp-cli-fixtures/compare/0.3.0...master) worth a `0.4.0`? 

We run `wp package install hellonico/wp-cli-fixtures` as part of our setup and would be good to be able to use `wp package install hellonico/wp-cli-fixtures:@stable` with the new features now in master.

**Comment by nlemoine** [comment]
Hi @jenkoian!

Just released 0.4.0, sorry for the late answer, I've been quite busy.
