### ISSUE TITLE
New release with updated FakerPHP dependencies and fix for method signature matching

### ISSUE THREAD

**Issue by VanwildemeerschBrent** [nlemoine/wp-cli-fixtures#16]
On October 12 #13 was merged into the `main`-branch with the following fixes : 
* [PHP 8.1 fix for method signature matching change on Faker](https://github.com/nlemoine/wp-cli-fixtures/pull/13/commits/ebb425589f760980c1909c9e3bf440cafc349987)
* [Update dependency on Faker 1.20.0](https://github.com/nlemoine/wp-cli-fixtures/pull/13/commits/4de1be58dd39c80f9e3786a9aad5d1fc954ffe99) 

Could be useful to have these changes tagged for a new release
Currently, the Composer package has these changes only available on the `dev-main` version

![image](https://user-images.githubusercontent.com/29630705/207596734-ce1f6a71-3212-4d31-bbc6-464d1c6179e6.png)
![image](https://user-images.githubusercontent.com/29630705/207596766-4e11707c-1178-478a-b871-867fba0d315a.png)

**Comment by nlemoine** [comment]
Should be fixed in main, 1.0 is ready to go, can you give it a try?
